Models/Event.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Ticky.Models
{
    public class Event
    {
        public int EventId { get; set; }

        [ForeignKey("Category")]
        public int CategoryId { get; set; }
        public Category? Category { get; set; }

        [ForeignKey("Retailer")]
        public int RetailerId { get; set; }
        public Retailer? Retailer { get; set; }

        public string Name { get; set; }
        public int Seat { get; set; }
        public float Price { get; set; }
        public DateTime StartDate { get; set; }
        public string Address { get; set; }
        public string Url { get; set; }
    }
}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ticky.Data;
using Ticky.Models;

namespace Ticky.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly TickyContext _context;

        public CategoriesController(TickyContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index(int catid)
        {
            var events = _context.Events.Where(e => e.CategoryId == catid);
            ViewBag.Categories = _context.Categories.ToList();
            return View(await events.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .SingleAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,Name")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .SingleAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'TickyContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.CategoryId == id)).GetValueOrDefault();
        }
    }
}

Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ticky.Data;
using Ticky.Models;

namespace Ticky.Controllers
{
    public class EventsController : Controller
    {
        private readonly TickyContext _context;

        public EventsController(TickyContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var TickyContext = _context.Events.Include(a => a.Category).Include(a => a.Retailer);
            ViewBag.Categories = _context.Categories.ToList();
            return View(await TickyContext.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Index(string SearchString)
        {
            //return _context.Events != null ? 
            //            View(await _context.Events.ToListAsync()) :
            //            Problem("Entity set 'WebApplication5Context.Events'  is null.");
            ViewData["CurrentFilter"] = SearchString;
            var events = from p in _context.Events.Include(a => a.Category).Include(a => a.Retailer)
                         select p;
            ViewBag.Categories = _context.Categories.ToList();
            if (!String.IsNullOrEmpty(SearchString))
            {
                events = events.Where(p => p.Name.Contains(SearchString));
                return View(events);
            }
            else
            {
                var webApplication5Context = _context.Events.Include(a => a.Category).Include(a => a.Retailer);
                return View(await webApplication5Context.ToListAsync());
            }
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var aevent = await _context.Events
                .Include(a => a.Category)
                .Include(a => a.Retailer)
                .SingleAsync(m => m.EventId == id);
            if (aevent == null)
            {
                return NotFound();
            }

            return View(aevent);
        }

        // GET: Events/Create
        [Authorize(Policy = "isRetailer")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name");
            
            return View();
        }
        [Authorize(Policy = "IsRetailer")]
        public IActionResult Manage()
        {
            int accountId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
			int retailerId = _context.Retailers.First(r => r.AccountId == accountId).RetailerId;
            var events = _context.Events
                .Include(e => e.Category)
                .Where(e => e.RetailerId == retailerId);
            return View(events);
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,Name,Seat,Price,StartDate,Address, Url")] Event aevent)
        {
            int accountid = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            aevent.RetailerId = _context.Retailers.Single(r => r.AccountId == accountid).RetailerId;
            if (ModelState.IsValid)
            {
                _context.Add(aevent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", aevent.CategoryId);
            return View(aevent);
        }

        // GET: Events/Edit/5
        [Authorize(Policy = "isRetailer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var aevent = await _context.Events.FindAsync(id);
            if (aevent == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", aevent.CategoryId);
            return View(aevent);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId, RetailerId, CategoryId,Name,Seat,Price,StartDate,Address, Url")] Event aevent)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aevent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(aevent.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Manage));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", aevent.CategoryId);
            return View(aevent);
        }

        // GET: Events/Delete/5
        [Authorize(Policy = "isRetailer")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var aevent = await _context.Events.Include(e => e.Category).Include(e => e.Retailer)
                .SingleAsync(m => m.EventId == id);
            if (aevent == null)
            {
                return NotFound();
            }

            return View(aevent);
        }

        // POST: Events/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Events == null)
            {
                return Problem("Entity set 'TickyContext.Events'  is null.");
            }
            var aevent = await _context.Events.FindAsync(id);
            if (aevent != null)
            {
                _context.Events.Remove(aevent);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
          return (_context.Events?.Any(e => e.EventId == id)).GetValueOrDefault();
        }
    }
}

Views/Events/Create.cshtml
@model Ticky.Models.Event

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seat" class="control-label"></label>
                <input asp-for="Seat" class="form-control" />
                <span asp-validation-for="Seat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Events/Details.cshtml
@model Ticky.Models.Event

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="header__logo">
                    <a href="."><img style="height: 50%; width: 50%;" src="~/img/logo.png" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6">
                <nav class="header__menu">
                    <ul>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Events" asp-action="Index">Shop</a></li>
                        @if (@User.IsInRole("3"))
                        {
                            <li><a asp-area="" asp-controller="Events" asp-action="Manage">Manage</a></li>
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Order" asp-action="Index">Cart</a></li>
                        }

                        <li><a href="./#blog-section">Blog</a></li>
                        <li><a href="./#footer">Contact</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3">
                <div class="header__cart">
                    <ul>
                        @if (@User.IsInRole("2"))
                        {
                            <li><a asp-area="" asp-controller="Cart" asp-action="Index"><i class="fa fa-shopping-bag"></i></a></li>
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Cart" asp-action="Index"><i class="fa fa-file"></i></a></li>
                        }
                    </ul>
                    <div class="header__top__right__auth">
                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <span>Hi @User.Identity.Name</span>
                            <a asp-area="" asp-controller="Accounts" asp-action="Logout"><i class="fa fa-user"></i> Logout</a>
                        }
                        else
                        {
                            <a asp-area="" asp-controller="Accounts" asp-action="Login"><i class="fa fa-user"></i> Login</a>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="humberger__open">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</header>
<!-- Header Section End -->
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="https://images.pexels.com/photos/2747449/pexels-photo-2747449.jpeg?cs=srgb&dl=pexels-wolfgang-2747449.jpg&fm=jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Ticky Box</h2>
                    <div class="breadcrumb__option">
                        <a href=".">Home</a>
                        <span>Event Detail</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Product Details Section Begin -->
<section class="product-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <div class="product__details__pic">
                    <div class="product__details__pic__item">
                        <img class="product__details__pic__item--large"
                             src="@Model.Url" alt="">
                    </div>
                </div>
            </div>
<form asp-action="Add" asp-controller="Order">
                <div class="">
                    <div class="product__details__text">
                        <h3>@Model.Name</h3>
                        <h4>Show Date: @Model.StartDate.Date.ToShortDateString()</h4>
                        <h4>Address: @Model.Address</h4>
                        <h4>Total Seats: @Model.Seat</h4>
                        <div class="product__details__price">$ @Model.Price</div>
                        <div class="product__details__quantity">
                            <div class="quantity">            
                                    @if (!User.IsInRole("3"))
                                    {
                                    <div class=""> 
                                        <input type="hidden" name="EventId" value="@Model.EventId" />
                                        <input type="number" name="quantity" value="1">
                                    </div>
                                    }
                            </div>
                        </div>
                        @if (!User.IsInRole("3"))
                        {
                            <button type="submit" class="primary-btn">ADD TO CART</button>
                        }
                        <div class="share">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
</form>
            
        </div>
    </div>
</section>
<!-- Product Details Section End -->
<!-- Related Product Section Begin -->
<section class="related-product">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title related__product__title">
                    <h2>Related Product</h2>
                </div>
            </div>
        </div>
        <div class="row">         
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="product__item">
                    <div class="product__item__pic set-bg" data-setbg="img/product/product-3.jpg">
                        <ul class="product__item__pic__hover">
                            <li><a href="#"><i class="fa fa-heart"></i></a></li>
                            <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                            <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="product__item__text">
                        <h6><a href="#">Crab Pool Security</a></h6>
                        <h5>$30.00</h5>
                    </div>
                </div>
            </div>           
        </div>
    </div>
</section>
<!-- Related Product Section End -->

Views/Events/Edit.cshtml
@model Ticky.Models.Event

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action ="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId" autoselect=""></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <input asp-for="RetailerId" class="form-control" type="hidden" value="@Model.RetailerId" />
            <input asp-for="EventId" class="form-control" type="hidden" value="@Model.EventId" />
            <div class="form-group">
                <label asp-for="Seat" class="control-label"></label>
                <input asp-for="Seat" class="form-control" />
                <span asp-validation-for="Seat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="modal-footer">
                <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                <input type="submit" class="btn btn-info" value="Save">
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Manage" asp-controller="Events">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Events/Index.cshtml
@model IEnumerable<Ticky.Models.Event>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="header__logo">
                    <a asp-action="Index" asp-controller="Home"><img style="height: 50%; width: 50%;" src="~/img/logo.png" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6">
                <nav class="header__menu">
                    <ul>
                        <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                        <li class="active"><a asp-area="" asp-controller="Events" asp-action="Index">Shop</a></li>
                        @if (@User.IsInRole("3"))
                        {
                            <li><a asp-area="" asp-controller="Events" asp-action="Manage">Manage</a></li>
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Order" asp-action="Index">Cart</a></li>
                        }

                        <li><a href="./#blog-section">Blog</a></li>
                        <li><a href="./#footer">Contact</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3">
                <div class="header__cart">
                    <ul>
                        @if (@User.IsInRole("2"))
                        {
                            <li><a asp-area="" asp-controller="Order" asp-action="Index"><i class="fa fa-shopping-bag"></i></a></li>
                        }
                        else if (User.IsInRole("3"))
                        {
                            <li><a asp-area="" asp-controller="Events" asp-action="Manage"><i class="fa fa-file"></i></a></li>
                        }
                    <div class="header__top__right__auth">
                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <span>Hi @User.Identity.Name</span>
                            <a asp-area="" asp-controller="Accounts" asp-action="Logout"><i class="fa fa-user"></i> Logout</a>
                        }
                        else
                        {
                            <a asp-area="" asp-controller="Accounts" asp-action="Login"><i class="fa fa-user"></i> Login</a>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="humberger__open">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</header>
<!-- Header Section End -->
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="https://images.pexels.com/photos/2747449/pexels-photo-2747449.jpeg?cs=srgb&dl=pexels-wolfgang-2747449.jpg&fm=jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Ticky Box</h2>
                    <div class="breadcrumb__option">
                        <a href=".">Home</a>
                        <span>All Events</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Product Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-5">
                <div class="sidebar">
                    <div class="sidebar__item">
                        <h4>All Categories</h4>
                        <ul>
                            @foreach (var cat in ViewBag.Categories)
                            {
                                <li>
                                    <a asp-controller="Categories" asp-action="Index" asp-route-categoryID="@cat.CategoryId">
                                        @cat.Name
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-7">
                <div class="product__discount">
                    <div class="section-title product__discount__title">
                        <h2>All events</h2>
                    </div>
                    <div class="filter__item">
                        <div class="filter__found">
                            @if (User.Identity != null && User.Identity.IsAuthenticated)
                            {
                                <span>Hi @User.Identity.Name</span>
                                <a asp-area="" asp-controller="Accounts" asp-action="Logout"><i class="fa fa-user"></i> Logout</a>
                            }
                            <h6><span>0</span> Products found</h6>
                        </div>
                    </div>
                </div>
               
                <div class="row">
                    @foreach (var e in Model)
                        {
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg="@e.Url">
                                    <ul class="product__item__pic__hover">
                                        <li><a asp-action="Details" asp-controller="Events" asp-route-id="@e.EventId"><i class="fa fa-book"></i></a></li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6><a asp-action="Details" asp-controller="Events" asp-route-id="@e.EventId">@e.Name</a></h6>
                                    <h5>$ @e.Price</h5>
                                </div>
                            </div>
                        </div>
                    }                 
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Product Section End -->